use macroquad::{
    audio::{Sound, load_sound},
    text::{Font, load_ttf_font},
    texture::{Texture2D, load_texture},
};
use std::collections::HashMap;

/// Central asset manager storing loaded textures, sounds, and fonts.
/// Serves as the single source of truth for game resources.
#[derive(Clone, Default)]
pub struct Assets {
    textures: HashMap<String, Texture2D>,
    sequences: HashMap<String, Vec<Texture2D>>,
    sounds: HashMap<String, Sound>,
    fonts: HashMap<String, Font>,
}

impl Assets {
    /// Creates a new empty [`Assets`] manager.
    pub fn new() -> Self {
        Self {
            textures: HashMap::new(),
            sequences: HashMap::new(),
            sounds: HashMap::new(),
            fonts: HashMap::new(),
        }
    }

    /// Asynchronously loads a texture from the given file path and stores it under `name`.
    pub async fn load_texture(
        &mut self,
        name: &str,
        path: &str,
    ) -> Result<Texture2D, macroquad::Error> {
        let texture = load_texture(path).await?;
        self.textures.insert(name.to_string(), texture.clone());
        Ok(texture)
    }

    /// Manually inserts a pre-created [`Texture2D`] under `name`.
    pub fn insert_texture(&mut self, name: &str, texture: Texture2D) {
        self.textures.insert(name.to_string(), texture);
    }

    /// Retrieves a reference to a stored texture by name.
    pub fn get_texture(&self, name: &str) -> Option<&Texture2D> {
        self.textures.get(name)
    }

    /// Asynchronously loads a sequence of animation frame textures generated by calling `path_fn(0..count)` and stores them under `name`.
    ///
    /// Using a closure rather than a string format pattern eliminates zero-padding issues (e.g. `rec_001.png`).
    ///
    /// # Example
    /// ```rust,ignore
    /// assets.load_frame_sequence("video", |i| format!("assets/rec_{:03}.png", i), 30).await?;
    /// ```
    pub async fn load_frame_sequence(
        &mut self,
        name: &str,
        path_fn: impl Fn(usize) -> String,
        count: usize,
    ) -> Result<Vec<Texture2D>, macroquad::Error> {
        let mut frames = Vec::with_capacity(count);
        for i in 0..count {
            let path = path_fn(i);
            let texture = load_texture(&path).await?;
            frames.push(texture);
        }
        self.sequences.insert(name.to_string(), frames.clone());
        Ok(frames)
    }

    /// Manually inserts a pre-loaded texture frame sequence under `name`.
    pub fn insert_sequence(&mut self, name: &str, sequence: Vec<Texture2D>) {
        self.sequences.insert(name.to_string(), sequence);
    }

    /// Retrieves a reference to a stored frame sequence by name.
    pub fn get_sequence(&self, name: &str) -> Option<&[Texture2D]> {
        self.sequences.get(name).map(|v| v.as_slice())
    }

    /// Asynchronously loads a sound effect from the given file path and stores it under `name`.
    pub async fn load_sound(&mut self, name: &str, path: &str) -> Result<Sound, macroquad::Error> {
        let sound = load_sound(path).await?;
        self.sounds.insert(name.to_string(), sound.clone());
        Ok(sound)
    }

    /// Manually inserts a pre-loaded [`Sound`] handle under `name`.
    pub fn insert_sound(&mut self, name: &str, sound: Sound) {
        self.sounds.insert(name.to_string(), sound);
    }

    /// Retrieves a reference to a stored sound by name.
    pub fn get_sound(&self, name: &str) -> Option<&Sound> {
        self.sounds.get(name)
    }

    /// Asynchronously loads a TTF font from the given file path and stores it under `name`.
    pub async fn load_font(&mut self, name: &str, path: &str) -> Result<Font, macroquad::Error> {
        let font = load_ttf_font(path).await?;
        self.fonts.insert(name.to_string(), font.clone());
        Ok(font)
    }

    /// Retrieves a reference to a stored font by name.
    pub fn get_font(&self, name: &str) -> Option<&Font> {
        self.fonts.get(name)
    }
}
