use macroquad::{
    audio::{Sound, load_sound},
    text::{Font, load_ttf_font},
    texture::{Texture2D, load_texture},
};
use std::collections::HashMap;

/// Central asset manager storing loaded textures, sounds, and fonts.
/// Serves as the single source of truth for game resources.
#[derive(Clone, Default)]
pub struct Assets {
    textures: HashMap<String, Texture2D>,
    sequences: HashMap<String, Vec<Texture2D>>,
    sounds: HashMap<String, Sound>,
    fonts: HashMap<String, Font>,
}

impl Assets {
    /// Creates a new empty [`Assets`] manager.
    pub fn new() -> Self {
        Self {
            textures: HashMap::new(),
            sequences: HashMap::new(),
            sounds: HashMap::new(),
            fonts: HashMap::new(),
        }
    }

    /// Asynchronously loads a texture from the given file path and stores it under `name`.
    /// Automatically normalizes leading slashes (e.g. `"/assets/img.png"` -> `"assets/img.png"`).
    pub async fn load_texture(
        &mut self,
        name: &str,
        path: &str,
    ) -> Result<Texture2D, macroquad::Error> {
        let clean_path = path.trim_start_matches('/').trim_start_matches('\\');
        let texture = match load_texture(clean_path).await {
            Ok(t) => t,
            Err(e1) => match load_texture(path).await {
                Ok(t) => t,
                Err(e2) => {
                    eprintln!(
                        "[RustedEngine Assets] Failed to load texture '{}' from path '{}' (clean: '{}'): {:?} / {:?}",
                        name, path, clean_path, e1, e2
                    );
                    return Err(e2);
                }
            },
        };
        self.textures.insert(name.to_string(), texture.clone());
        Ok(texture)
    }

    /// Asynchronously loads a pixel-art texture with [`FilterMode::Nearest`](macroquad::texture::FilterMode::Nearest) filtering enabled.
    pub async fn load_texture_nearest(
        &mut self,
        name: &str,
        path: &str,
    ) -> Result<Texture2D, macroquad::Error> {
        let texture = self.load_texture(name, path).await?;
        texture.set_filter(macroquad::texture::FilterMode::Nearest);
        Ok(texture)
    }

    /// Manually inserts a pre-created [`Texture2D`] under `name`.
    pub fn insert_texture(&mut self, name: &str, texture: Texture2D) {
        self.textures.insert(name.to_string(), texture);
    }

    /// Retrieves a reference to a stored texture by name.
    pub fn get_texture(&self, name: &str) -> Option<&Texture2D> {
        self.textures.get(name)
    }

    /// Asynchronously loads a sequence of animation frame textures generated by calling `path_fn(0..count)` and stores them under `name`.
    ///
    /// Using a closure rather than a string format pattern eliminates zero-padding issues (e.g. `rec_001.png`).
    ///
    /// # Example
    /// ```rust,ignore
    /// assets.load_frame_sequence("video", |i| format!("assets/rec_{:03}.png", i), 30).await?;
    /// ```
    pub async fn load_frame_sequence(
        &mut self,
        name: &str,
        path_fn: impl Fn(usize) -> String,
        count: usize,
    ) -> Result<Vec<Texture2D>, macroquad::Error> {
        let mut frames = Vec::with_capacity(count);
        for i in 0..count {
            let p = path_fn(i);
            let clean_p = p.trim_start_matches('/').trim_start_matches('\\');
            let texture = match load_texture(clean_p).await {
                Ok(t) => t,
                Err(_) => load_texture(&p).await?,
            };
            frames.push(texture);
        }
        self.sequences.insert(name.to_string(), frames.clone());
        Ok(frames)
    }

    /// Manually inserts a pre-loaded texture frame sequence under `name`.
    pub fn insert_sequence(&mut self, name: &str, sequence: Vec<Texture2D>) {
        self.sequences.insert(name.to_string(), sequence);
    }

    /// Retrieves a reference to a stored frame sequence by name.
    pub fn get_sequence(&self, name: &str) -> Option<&[Texture2D]> {
        self.sequences.get(name).map(|v| v.as_slice())
    }

    /// Asynchronously loads a sound effect from the given file path and stores it under `name`.
    pub async fn load_sound(&mut self, name: &str, path: &str) -> Result<Sound, macroquad::Error> {
        let clean_path = path.trim_start_matches('/').trim_start_matches('\\');
        let sound = match load_sound(clean_path).await {
            Ok(s) => s,
            Err(_e1) => match load_sound(path).await {
                Ok(s) => s,
                Err(e2) => {
                    eprintln!(
                        "[RustedEngine Assets] Failed to load sound '{}' from path '{}': {:?}",
                        name, path, e2
                    );
                    return Err(e2);
                }
            },
        };
        self.sounds.insert(name.to_string(), sound.clone());
        Ok(sound)
    }

    /// Manually inserts a pre-loaded [`Sound`] handle under `name`.
    pub fn insert_sound(&mut self, name: &str, sound: Sound) {
        self.sounds.insert(name.to_string(), sound);
    }

    /// Retrieves a reference to a stored sound by name.
    pub fn get_sound(&self, name: &str) -> Option<&Sound> {
        self.sounds.get(name)
    }

    /// Asynchronously loads a TTF font from the given file path and stores it under `name`.
    ///
    /// # Known Limitation
    /// Macroquad's [`Font`] type does not expose a public API to configure glyph atlas texture filtering
    /// (e.g. [`FilterMode::Nearest`](macroquad::texture::FilterMode::Nearest)). Text rendered inside a virtual resolution target ([`Engine::with_virtual_resolution`](crate::engine::Engine::with_virtual_resolution))
    /// inherits the nearest-neighbor filtering of the underlying [`SceneRenderTarget`](crate::postprocess::SceneRenderTarget) texture when composited to screen.
    pub async fn load_font(&mut self, name: &str, path: &str) -> Result<Font, macroquad::Error> {
        let clean_path = path.trim_start_matches('/').trim_start_matches('\\');
        let font = match load_ttf_font(clean_path).await {
            Ok(f) => f,
            Err(_e1) => match load_ttf_font(path).await {
                Ok(f) => f,
                Err(e2) => {
                    eprintln!(
                        "[RustedEngine Assets] Failed to load font '{}' from path '{}': {:?}",
                        name, path, e2
                    );
                    return Err(e2);
                }
            },
        };
        self.fonts.insert(name.to_string(), font.clone());
        Ok(font)
    }

    /// Retrieves a reference to a stored font by name.
    pub fn get_font(&self, name: &str) -> Option<&Font> {
        self.fonts.get(name)
    }

    /// Unloads and removes a stored texture by name. Returns `true` if texture was present.
    pub fn unload_texture(&mut self, name: &str) -> bool {
        self.textures.remove(name).is_some()
    }

    /// Unloads and removes a stored texture frame sequence by name. Returns `true` if present.
    pub fn unload_sequence(&mut self, name: &str) -> bool {
        self.sequences.remove(name).is_some()
    }

    /// Unloads and removes a stored sound effect by name. Returns `true` if present.
    pub fn unload_sound(&mut self, name: &str) -> bool {
        self.sounds.remove(name).is_some()
    }

    /// Unloads and removes a stored font by name. Returns `true` if present.
    pub fn unload_font(&mut self, name: &str) -> bool {
        self.fonts.remove(name).is_some()
    }

    /// Clears and unloads all stored textures, frame sequences, sounds, and fonts.
    pub fn clear_all(&mut self) {
        self.textures.clear();
        self.sequences.clear();
        self.sounds.clear();
        self.fonts.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_asset_unloading() {
        let mut assets = Assets::new();
        assert_eq!(assets.get_texture("hero"), None);
        assert!(!assets.unload_texture("hero"));
        assert!(!assets.unload_sound("boom"));
        assert!(!assets.unload_font("main"));
        assets.clear_all();
    }
}
