//! Prelude re-exporting common structs, traits, enums, and macros for easy importing via `use rusted_engine::prelude::*;`.

pub use crate::{
    column, row, scene, ui_vec,
    actions::ActionMap,
    animated_texture::AnimatedSprite,
    asset_manager::Assets,
    audio::{AmbientPool, Audio},
    bitmap_font::{BitmapFont, GlyphInfo, register_font_id},
    camera::Camera,
    colors,
    content::{ContentError, load_content, load_content_dir},
    draggable::{DragState, Draggable},
    engine::{Context, CustomCursor, Engine},
    events::EventBus,
    geometry::{Capsule, Circle, Segment},
    input::Input,
    math::{Vec2Ext, smooth_damp, smooth_damp_vec2},
    object::{Behavior, Clickable, GameObject, Logic, LogicObject, Rectangle, Side, Sprite},
    panel_manager::{Panel, PanelId, PanelManager},
    particles::{Particle, ParticleEmitter},
    postprocess::{PostProcess, SceneRenderTarget},
    resources::Resources,
    rng::{
        Noise, Rng, ShuffleBag, WeightedList, random_angle, random_bool, random_choose,
        random_choose_mut, random_color, random_in_annulus, random_in_circle, random_in_rect,
        random_in_sector, random_in_triangle, random_normal, random_on_circle,
        random_on_rect_perimeter, random_on_segment, random_range, random_range_i32,
        random_range_usize, random_sample, random_shuffle, random_sign, random_spread,
    },
    save_system::{SaveError, SaveSlotMeta, SaveSystem},
    scene::{Scene, SceneChanged, SceneManager},
    sequence::{Sequence, SequenceBuilder, Step},
    state::{StateStore, StateValue},
    tilemap::Tilemap,
    time::{Time, Timer},
    trigger::{Trigger, TriggerSystem},
    tween::{Easing, Tween, TweenVec2},
    ui::{
        Align, Button, Checkbox, Column, Container, CrossAxisAlignment, Gap, Grid, HBox, Image, ImageObject,
        IntoUIObject, LayoutAlign, LayoutJustify, MainAxisAlignment, Margin, Padding, Panel as UiPanel,
        ProgressBar, RevealMode, RichText, RichTextObject, Row, ScrollMode, Slider, Text, TextAlign, TextAlignment, TextField,
        TextFieldObject, TextLog, TextLogObject, TextObject, UIAnchor, VBox,
        UI, draw_nine_slice, margin, padding, parse_color, parse_rich_text, rich_text, Tooltip,
    },
    window::Window,
    world,
    world::{Object, World},
    world_objects,
};
